import { ImportMetaEnv } from 'InvestCommon/types/vite-env.d';

let env = {
  KRATOS_URL: '',
  PLAID_URL: '',
  FRONTEND_URL: '',
  INVESTMENT_URL: '',
  OFFER_URL: '',
  ESIGN_URL: '',
  USER_URL: '',
  HELLOSIGN_CLIENT_ID: '',
  NOTIFICATION_URL: '',
  HUBSPOTFORM: '',
  HUBSPOTPORTAL_ID: '',
  ACCREDITATION_URL: '',
  PAYMENTS_URL: '',
  WALLET_URL: '',
  FILER_URL: '',
  HUBSPOT_FORM_ID_RECEIVE_LATEST_NEWS: '',
  HUBSPOT_FORM_ID_CONTACT_US: '',
  HUBSPOT_FORM_ID_INVESTMENT_OBJECTIVES: '',
  HUBSPOT_FORM_ID_PERSONAL_INFORMATION: '',
  HUBSPOT_FORM_ID_TRUSTED_CONTACT: '',
  HUBSPOT_FORM_ID_BACKGROUND_INFORMATION: '',
};

export const setEnv = (envLocal: ImportMetaEnv) => {
    env.KRATOS_URL= envLocal.VITE_KRATOS_URL;
    env.PLAID_URL= envLocal.VITE_PLAID_URL;
    env.FRONTEND_URL= envLocal.VITE_FRONTEND;
    env.INVESTMENT_URL= envLocal.VITE_INVESTMENT_URL;
    env.OFFER_URL= envLocal.VITE_OFFER_URL;
    env.ESIGN_URL= envLocal.VITE_ESIGN_URL;
    env.USER_URL= envLocal.VITE_USER_URL;
    env.HELLOSIGN_CLIENT_ID= envLocal.VITE_HELLOSIGN_CLIENT_ID;
    env.NOTIFICATION_URL= envLocal.VITE_NOTIFICATION_URL;
    env.HUBSPOTFORM= envLocal.VITE_HUBSPOTFORM;
    env.HUBSPOTPORTAL_ID= envLocal.VITE_HUBSPOTPORTAL_ID;
    env.ACCREDITATION_URL= envLocal.VITE_ACCREDITATION_URL;
    env.PAYMENTS_URL= envLocal.VITE_PAYMENTS_URL;
    env.WALLET_URL= envLocal.VITE_WALLET_URL;
    env.FILER_URL= envLocal.VITE_FILER_URL;
    env.HUBSPOT_FORM_ID_RECEIVE_LATEST_NEWS= envLocal.VITE_HUBSPOT_FORM_ID_RECEIVE_LATEST_NEWS;
    env.HUBSPOT_FORM_ID_CONTACT_US= envLocal.VITE_HUBSPOT_FORM_ID_CONTACT_US;
    env.HUBSPOT_FORM_ID_INVESTMENT_OBJECTIVES= envLocal.VITE_HUBSPOT_FORM_ID_INVESTMENT_OBJECTIVES;
    env.HUBSPOT_FORM_ID_PERSONAL_INFORMATION= envLocal.VITE_HUBSPOT_FORM_ID_PERSONAL_INFORMATION;
    env.HUBSPOT_FORM_ID_TRUSTED_CONTACT= envLocal.VITE_HUBSPOT_FORM_ID_TRUSTED_CONTACT;
    env.HUBSPOT_FORM_ID_BACKGROUND_INFORMATION= envLocal.VITE_HUBSPOT_FORM_ID_BACKGROUND_INFORMATION;
}

export default env;
