/// <reference types="vite/client" />

export interface ImportMetaEnv {
  VITE_KRATOS_URL: string;
  VITE_PLAID_URL: string;
  VITE_FRONTEND: string;
  VITE_INVESTMENT_URL: string;
  VITE_OFFER_URL: string;
  VITE_ESIGN_URL: string;
  VITE_USER_URL: string;
  VITE_HELLOSIGN_CLIENT_ID: string;
  VITE_NOTIFICATION_URL: string;
  VITE_HUBSPOTFORM: string;
  VITE_HUBSPOTPORTAL_ID: string;
  VITE_ACCREDITATION_URL: string;
  VITE_PAYMENTS_URL: string;
  VITE_WALLET_URL: string;
  VITE_EVM_URL: string;
  VITE_FILER_URL: string;
  VITE_DISTRIBUTIONS_URL: string;
  VITE_ANALYTIC_URL: string;
  VITE_HUBSPOT_FORM_ID_RECEIVE_LATEST_NEWS: string;
  VITE_HUBSPOT_FORM_ID_CONTACT_US: string;
  VITE_HUBSPOT_FORM_ID_INVESTMENT_OBJECTIVES: string;
  VITE_HUBSPOT_FORM_ID_PERSONAL_INFORMATION: string;
  VITE_HUBSPOT_FORM_ID_TRUSTED_CONTACT: string;
  VITE_HUBSPOT_FORM_ID_BACKGROUND_INFORMATION: string;
  VITE_HUBSPOT_FORM_ID_KYC: string;
  VITE_HUBSPOT_FORM_ID_BENEFICIAL_OWNERS: string;
  readonly VITE_GIT_HASH?: string;
}
