export const userData = {
  dob: '1975-01-18',
  ssn: '6789',
  city: '123 Main St.',
  phone: '12345678909',
  state: 'IN',
  country: 'US',
  address1: '123 Main St.',
  address2: '#100',
  zip_code: '46001',
  middle_name: '',
  last_name: 'Knope',
  first_name: 'Leslie',
  ip_address: '176.67.20.244',
  nc_link_id: '1600578',
  citizenship: 'U.S. Citizen',
  nc_party_id: 'P2262908',
  nc_account_nickname: 'CEFCU Bank',
  nc_account_bank_name: 'JP Morgan',
  profile_id: 6,
  profile_type: 'individual',
  user_id: 13,
  escrow_id: 'A2647332',
  kyc_status: 'approved',
  accreditation_status: 'pending',
  total_distributions: 0,
  total_investments: 0,
  total_investments_12_months: 0,
  risk_involved: true,
  resell_difficulties: true,
  educational_materials: true,
  cancelation_restrictions: true,
  no_legal_advices_from_company: true,
  // reg_cf: {
  //   net_worth: 2000000,
  //   annual_income: 2000000,
  //   limitation_rule: true,
  //   invested_external: 0,
  //   limitation_rule_confirmation: true
  // },
};

export const userProfileData = {
  dob: '1975-01-18',
  ssn: '6789',
  city: '123 Main St.',
  phone: '12345678909',
  state: 'IN',
  country: 'US',
  address1: '123 Main St.',
  address2: '#100',
  zip_code: '46001',
  middle_name: '',
  last_name: 'Knope',
  first_name: 'Leslie',
  citizenship: 'U.S. Citizen',
};

export const UserIdentity = {
  id: 125,
  escrow_id: 'A2873882',
  type: 'individual',
  data: {
    dob: '1975-01-18',
    ssn: '123456789',
    city: 'Pawnee',
    phone: '123-456-7890',
    state: 'IN',
    reg_cf: {
      net_worth: 0.0,
      annual_income: 0.0,
      limitation_rule: true,
      invested_external: 0.0,
      limitation_rule_confirmation: true,
    },
    country: 'US',
    address1: '123 Main St.',
    address2: 'Suite 156',
    zip_code: '24446',
    last_name: 'Klyusa',
    employment: { type: 'Employed (full-time)' },
    first_name: 'Nelya',
    ip_address: '193.34.172.203',
    nc_link_id: '1793946',
    beneficiary: {
      dob: '2024-03-14',
      email: 'sdf',
      phone: 'sdf',
      last_name: 'sdf',
      first_name: 'sdf',
      relationship_type: 'sdf',
    },
    citizenship: 'U.S. Citizen',
    middle_name: '\u0432\u0432',
    nc_party_id: 'P2441977',
    risk_involved: false,
    finra_affiliated: {
      correspondence: true,
      member_firm_name: 'sdf',
      member_association: true,
      compliance_contract_name: 'sdf',
      compliance_contract_email: '',
    },
    accredited_investor: { explanation: '', is_accredited: false },
    resell_difficulties: false,
    educational_materials: false,
    investment_objectives: {
      duration: '1 to 3 years',
      objectives: 'Growth',
      risk_comfort: 'High Risk',
      years_experience: 0,
      importance_of_access: 'Somewhat Important',
    },
    irs_backup_withholding: true,
    ten_percent_shareholder: { ticker_symbol_list: 'sdf', shareholder_association: true },
    no_legal_advices_from_company: true,
  },
  kyc_status: 'approved',
  kyc_data: [
    {
      status: 'approved',
      created_at: '2024-03-15T07:51:10Z',
      completed_at: '2024-03-15T07:50:53Z',
    },
    {
      status: 'approved',
      created_at: '2024-03-15 07:51:14+00:00',
      completed_at: '2024-03-15 07:51:14+00:00',
    },
  ],
  accreditation_status: 'in_progress',
  accreditation_data: [
    {
      status: 'in_progress',
      created_at: '2024-03-15 07:52:15+00:00',
      completed_at: '-infinity',
      nc_accreditated_status: 'pending',
    },
  ],
  kyc_at: '2024-03-15 07:51:14+00:00',
  accreditation_at: '0001-01-01 00:00:00',
  wallet: { id: 258, status: 'verified' },
  total_investments: 1217.46,
  total_investments_12_months: 1217.46,
  total_distributions: 0.0,
  avarange_annual: 0.0,
  user_id: 125,
};


export const userUserData = {
  id: 151,
  last_login: '0001-01-01T00:00:00',
  created_at: '2024-03-25T18:02:43.617122+00:00',
  data: {
    reg_cf: {
      net_worth: 0.0,
      annual_income: 0.0,
      limitation_rule: false,
      invested_external: 0.0,
      limitation_rule_confirmation: false,
    },
    accredited_investor: { explanation: '', is_accredited: false },
  },
  profiles: [
    {
      id: 151,
      user_id: 151,
      type: 'individual',
      data: { last_name: 'Klyusa', first_name: 'Nelya' },
      kyc_id: null,
      kyc_status: 'none',
      kyc_data: [],
      accreditation_id: null,
      accreditation_status: 'new',
      accreditation_data: [],
      escrow_id: '',
      kyc_at: '0001-01-01T00:00:00',
      accreditation_at: '0001-01-01T00:00:00',
      created_at: '2024-03-25T18:02:43.621552+00:00',
      updated_at: '2024-03-25T18:02:43.621552+00:00',
      wallet_id: null,
      total_investments: 0,
      total_investments_12_months: 0,
      total_distributions: 0.0,
      avarange_annual: 0.0,
    },
  ],
};

export const userIndividualJustRegisteredMock = {
  id: 178,
  escrow_id: '',
  type: 'individual',
  data: { last_name: 'Klyusa', first_name: 'Nelya' },
  kyc_status: 'none',
  kyc_data: '[]',
  accreditation_status: 'new',
  accreditation_data: '[]',
  kyc_at: '0001-01-01 00:00:00',
  accreditation_at: '0001-01-01 00:00:00',
  wallet: { id: null, status: null },
  total_investments: 0,
  total_investments_12_months: 0,
  total_distributions: 0.0,
  avarange_annual: 0.0,
  user_id: 178,
};

export const userIndividualOptionsMock = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  definitions: {
    AccreditedInvestor: {
      properties: {
        explanation: { title: 'explanation', type: 'string', maxLength: 1000 },
        is_accredited: { title: 'is_accredited', type: 'boolean' },
      },
      type: 'object',
      required: ['is_accredited'],
      additionalProperties: false,
    },
    InvestmentObjectives: {
      properties: {
        duration: { title: 'duration', type: 'string', maxLength: 500 },
        importance_of_access: { title: 'importance_of_access', type: 'string', maxLength: 500 },
        objectives: { title: 'objectives', type: 'string', maxLength: 500 },
        risk_comfort: { title: 'risk_comfort', type: 'string', maxLength: 500 },
        years_experience: {
          title: 'years_experience', type: 'integer', minimum: 0, maximum: 100,
        },
      },
      type: 'object',
      additionalProperties: false,
    },
    RegCF: {
      properties: {
        annual_income: {
          title: 'annual_income', type: 'number', format: 'float', minimum: 0,
        },
        invested_external: {
          title: 'invested_external',
          type: 'number',
          format: 'float',
          minimum: 0,
        },
        limitation_rule: { title: 'limitation_rule', type: 'boolean' },
        limitation_rule_confirmation: { title: 'limitation_rule_confirmation', type: 'boolean' },
        net_worth: {
          title: 'net_worth', type: 'number', format: 'float', minimum: 0,
        },
      },
      type: 'object',
      required: [
        'annual_income',
        'invested_external',
        'limitation_rule',
        'limitation_rule_confirmation',
        'net_worth',
      ],
      additionalProperties: false,
    },
    PatchIndividualProfile: {
      properties: {
        accredited_investor: { type: 'object', $ref: '#/definitions/AccreditedInvestor' },
        address1: { title: 'address1', type: 'string', minLength: 4 },
        address2: { title: 'address2', type: 'string' },
        annual_income: { title: 'annual_income', type: 'number', format: 'float' },
        beneficiary: { title: 'beneficiary', type: 'object', additionalProperties: {} },
        cancelation_restrictions: { title: 'cancelation_restrictions', type: 'boolean' },
        citizenship: { title: 'citizenship', type: 'string', minLength: 3 },
        city: { title: 'city', type: 'string', minLength: 2 },
        country: { title: 'country', type: 'string', minLength: 2 },
        dob: { title: 'dob', type: 'string', format: 'date' },
        educational_materials: { title: 'educational_materials', type: 'boolean' },
        employment: { title: 'employment', type: 'object', additionalProperties: {} },
        finra_affiliated: { title: 'finra_affiliated', type: 'object', additionalProperties: {} },
        first_name: { title: 'first_name', type: 'string', minLength: 2 },
        invested_external: { title: 'invested_external', type: 'number', format: 'float' },
        investment_objectives: { type: 'object', $ref: '#/definitions/InvestmentObjectives' },
        irs_backup_withholding: { title: 'irs_backup_withholding', type: 'boolean' },
        last_name: { title: 'last_name', type: 'string', minLength: 2 },
        limitation_rule: { title: 'limitation_rule', type: 'boolean' },
        limitation_rule_confirmation: { title: 'limitation_rule_confirmation', type: 'boolean' },
        middle_name: { title: 'middle_name', type: 'string' },
        net_worth: { title: 'net_worth', type: 'number', format: 'float' },
        no_legal_advices_from_company: { title: 'no_legal_advices_from_company', type: 'boolean' },
        phone: { title: 'phone', type: 'string', minLength: 9 },
        reg_cf: { type: 'object', $ref: '#/definitions/RegCF' },
        resell_difficulties: { title: 'resell_difficulties', type: 'boolean' },
        risk_involved: { title: 'risk_involved', type: 'boolean' },
        ssn: {
          title: 'ssn', type: 'string', minLength: 9, maxLength: 9,
        },
        state: { title: 'state', type: 'string', minLength: 2 },
        ten_percent_shareholder: {
          title: 'ten_percent_shareholder',
          type: 'object',
          additionalProperties: {},
        },
        zip_code: { title: 'zip_code', type: 'string', minLength: 5 },
      },
      type: 'object',
      required: [
        'address1',
        'citizenship',
        'city',
        'country',
        'dob',
        'first_name',
        'last_name',
        'phone',
        'ssn',
        'state',
        'zip_code',
      ],
      additionalProperties: false,
    },
  },
  $ref: '#/definitions/PatchIndividualProfile',
};

export const mockOwnershipStepOptions = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  definitions: {
    OwnershipStep: {
      properties: {
        address1: { title: 'address1', type: 'string', minLength: 4 }, address2: { title: 'address2', type: 'string', minLength: 3 }, citizenship: { title: 'citizenship', type: 'string', minLength: 3 }, city: { title: 'city', type: 'string', minLength: 2 }, country: { title: 'country', type: 'string', minLength: 2 }, dob: { title: 'dob', type: 'string', format: 'date' }, first_name: { title: 'first_name', type: 'string', minLength: 2 }, last_name: { title: 'last_name', type: 'string', minLength: 2 }, middle_name: { title: 'middle_name', type: 'string', minLength: 2 }, phone: { title: 'phone', type: 'string', minLength: 9 }, ssn: { title: 'ssn', type: 'string', minLength: 7 }, state: { title: 'state', type: 'string', minLength: 2 }, zip_code: { title: 'zip_code', type: 'string', minLength: 5 },
      },
      type: 'object',
      required: ['address1', 'citizenship', 'city', 'country', 'dob', 'first_name', 'last_name', 'phone', 'ssn', 'state', 'zip_code'],
      additionalProperties: false,
    },
  },
  $ref: '#/definitions/OwnershipStep',
};
